import { useState } from 'react'
import { avatarUrl } from '../profile/avatarCatalog'
import { AvatarPicker } from '../profile/AvatarPicker'

const links=[['navigator','Navigator','⌂'],['admin','Admin Home','◈'],['team','Team Management','♙'],['usage','Usage Analytics','▥'],['feedback','Feedback','□']]

export function AppShell({ profile, children, onLogout, onAvatarChange, onPasswordChange, currentView='navigator', onNavigate=()=>{} }) {
  const [open,setOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [avatarOpen,setAvatarOpen]=useState(false); const [passwordOpen,setPasswordOpen]=useState(false); const [message,setMessage]=useState('')
  const isAdmin=profile.role==='creator_admin'; const visibleLinks=isAdmin?links:links.slice(0,1)
  async function submitPassword(event){event.preventDefault();const form=new FormData(event.currentTarget);const password=String(form.get('password'));const confirm=String(form.get('confirm'));if(password.length<8)return setMessage('Password must be at least 8 characters.');if(password!==confirm)return setMessage('Passwords do not match.');await onPasswordChange?.(password);setMessage('Password changed.');setPasswordOpen(false)}
  return <div className="app-shell">
    <header className="app-header"><button className="menu-toggle" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>☰</button><div className="console-brand"><strong>Zoom</strong><span>Support Console</span></div><div className="header-context">Support workspace</div><button className="account-menu" aria-label={`${profile.username} account`} onClick={()=>setProfileOpen(!profileOpen)}>{avatarUrl(profile.avatar_id)?<img src={avatarUrl(profile.avatar_id)} alt=""/>:<span className="avatar-fallback">{profile.initials}</span>}<span className="account-copy"><strong>{profile.username}</strong><small>{isAdmin?'JA Admin':'Agent'}</small></span><span aria-hidden="true">⌄</span></button></header>
    <aside className={`sidebar ${open?'open':''}`}><div><p className="sidebar-label">Workspace</p><nav aria-label="Primary navigation">{visibleLinks.map(([id,label,icon])=><button key={id} className={currentView===id?'active':''} onClick={()=>{onNavigate(id);setOpen(false)}}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav></div><button className="logout-button" onClick={onLogout}>Logout</button></aside>
    <main className="app-main">{children}</main>
    {profileOpen&&<div className="modal-backdrop" role="presentation" onClick={event=>event.target===event.currentTarget&&setProfileOpen(false)}><div className="profile-panel" role="dialog" aria-modal="true" aria-labelledby="profile-title"><div className="profile-summary">{avatarUrl(profile.avatar_id)?<img src={avatarUrl(profile.avatar_id)} alt=""/>:<span className="avatar-fallback">{profile.initials}</span>}<div><h2 id="profile-title">My Profile</h2><strong>{profile.username}</strong><p>{profile.initials} · {isAdmin?'JA Admin':'Agent'}</p></div></div>{message&&<p className="success-message">{message}</p>}{avatarOpen?<AvatarPicker selectedId={profile.avatar_id} onCancel={()=>setAvatarOpen(false)} onSave={async id=>{await onAvatarChange?.(id);setAvatarOpen(false)}}/>:passwordOpen?<form onSubmit={submitPassword}><h3>Change Password</h3><label>New password<input name="password" type="password" autoComplete="new-password"/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password"/></label><div className="dialog-actions"><button type="button" onClick={()=>setPasswordOpen(false)}>Cancel</button><button>Save Password</button></div></form>:<div className="profile-actions"><button onClick={()=>setAvatarOpen(true)}>Change Avatar</button><button onClick={()=>setPasswordOpen(true)}>Change Password</button><button onClick={onLogout}>Logout</button></div>}</div></div>}
  </div>
}
