export const SCENARIO_SCRIPT_VERIFIED_AT = 'September 19, 2026'

export const SCENARIO_SCRIPTS = [
  {
    id: 'cant-join',
    label: 'Can’t Join',
    routeId: 'cant-join',
    opening: 'Let’s first confirm exactly where Zoom is stopping you. I’ll use the message on your screen to choose the correct joining path.',
    guidePhrase: 'If the invitation link is not working, let’s try the meeting details directly. Please open Zoom Workplace or zoom.us/join and enter the Meeting ID exactly as it was provided.',
    confirmPhrase: 'What do you see now—did Zoom accept the meeting details, or are you seeing a waiting screen or another message?',
    boundaryPhrase: 'We’ve completed the basic joining checks available to us. If Zoom still will not let you enter, the next step may need the meeting organizer to confirm access or your IT team to check a device or network restriction.',
  },
  {
    id: 'waiting-entry',
    label: 'Waiting to Get In',
    routeId: 'waiting-entry',
    opening: 'Let’s read the exact waiting message first, because “Waiting for host” and “Waiting Room” have different next steps.',
    guidePhrase: 'Please read the exact message on the Zoom screen to me. I’ll use that wording to determine whether we should wait for the host to start the meeting or whether admission is controlled by the host.',
    confirmPhrase: 'Does the message now show that the meeting has started, that you were admitted, or are you still on the same waiting screen?',
    boundaryPhrase: 'If you are in the Waiting Room or the meeting has not been started, that next action is controlled by the meeting host or organizer. We can explain the screen, but we cannot admit participants or start the organizer’s meeting.',
  },
  {
    id: 'cant-hear',
    label: 'Can’t Hear',
    routeId: 'cant-hear',
    opening: 'Since you’re already in the meeting, let’s check the audio path first. We’ll make sure Zoom is connected to the correct speaker before we look anywhere else.',
    guidePhrase: 'First, tell me whether you see Join Audio. If you do, please connect to meeting audio before we change any speaker setting.',
    confirmPhrase: 'Can you hear the meeting now, or can you hear Zoom’s speaker test through the device you selected?',
    boundaryPhrase: 'If Zoom is stable but there is still no sound after the approved audio checks, we’ll stop guessing and use the full approved audio process. If the device itself cannot produce sound, the next step belongs with the appropriate device or IT support.',
  },
  {
    id: 'cant-be-heard',
    label: 'They Can’t Hear Me',
    routeId: 'cant-be-heard',
    opening: 'Let’s check the microphone side first. We’ll confirm you’re unmuted, then make sure Zoom is listening to the correct microphone.',
    guidePhrase: 'Please look at the microphone control in Zoom. Does it say Mute or Unmute, and do you have any physical mute button on the headset or microphone?',
    confirmPhrase: 'Please speak normally for a moment. Does Zoom detect your voice, and can the other participants hear you now?',
    boundaryPhrase: 'If the device or operating system itself does not recognize the microphone after the basic checks, that is no longer limited to a Zoom setting. Please contact your IT or device support team for the system-level check.',
  },
  {
    id: 'camera-not-working',
    label: 'Camera',
    routeId: 'camera-not-working',
    opening: 'First let’s see whether your video is just turned off or whether Zoom is having trouble with the camera itself.',
    guidePhrase: 'Please look at the video control. If it says Start Video, select it once. If video is already on but the picture is black or missing, tell me that before we continue.',
    confirmPhrase: 'Do you see your camera preview now, and is it coming from the camera you intended to use?',
    boundaryPhrase: 'If the computer or phone itself does not recognize the camera, the remaining issue is outside a Zoom-only setting. The appropriate IT or device support team will need to check the hardware or system permission.',
  },
  {
    id: 'cant-share',
    label: 'Screen Share',
    routeId: 'cant-share',
    opening: 'Let’s first locate the Share control and confirm whether Zoom is blocking the action or whether the host controls the permission.',
    guidePhrase: 'Please look for Share or Share Screen in the meeting controls. Tell me whether you can select it and what happens when you do.',
    confirmPhrase: 'Can the other participants now see only the screen, application, or window you intended to share?',
    boundaryPhrase: 'If participant sharing is restricted by the host, we cannot bypass that permission. Please contact the meeting host or organizer. If the browser or operating system blocks screen capture, use the approved device permission path instead.',
  },
  {
    id: 'meeting-controls',
    label: 'Meeting Controls',
    routeId: 'meeting-controls',
    opening: 'Let’s identify the control you need and what buttons are visible on your Zoom screen before we assume anything is missing.',
    guidePhrase: 'Move your pointer inside the meeting window or tap the meeting if you are on mobile. Tell me which controls you can see, and we’ll locate the one you need from there.',
    confirmPhrase: 'Is the control visible now, and did opening it show the option you were trying to use?',
    boundaryPhrase: 'If the control is unavailable because of the caller’s role, host settings, account settings, or another permission boundary, we’ll stop there rather than trying to bypass the meeting configuration.',
  },
  {
    id: 'chat',
    label: 'Chat',
    routeId: 'chat',
    opening: 'Let’s locate Chat first and confirm whether the meeting currently allows the type of message you’re trying to send.',
    guidePhrase: 'Please open Chat from the meeting controls. Before sending anything, check the recipient so the message goes only to the person or group you intend.',
    confirmPhrase: 'Do you see the Chat panel now, and did the message go to the intended recipient?',
    boundaryPhrase: 'If Chat or a specific chat option is disabled by the host or account administrator, we cannot enable that permission from basic support. The meeting host or appropriate administrator owns that next step.',
  },
  {
    id: 'reactions',
    label: 'Reactions / Raise Hand',
    routeId: 'reactions',
    opening: 'Let’s open the reactions menu first. If you’re raising your hand, I’ll also show you how to lower it afterward because that one stays active until it’s cleared.',
    guidePhrase: 'Please look for React or Reactions. On mobile, check More if you do not see it on the main controls. Tell me when the reaction choices are visible.',
    confirmPhrase: 'Can you see the raised-hand indicator or the reaction you selected, and do you know how to remove it when you’re finished?',
    boundaryPhrase: 'If reactions are unavailable because the host or account administrator has disabled them, that is a meeting or account permission boundary and we should not try to bypass it.',
  },
  {
    id: 'bluetooth-headset',
    label: 'Bluetooth Headset',
    routeId: 'bluetooth-headset',
    opening: 'Let’s separate the Bluetooth connection from the Zoom setting first. We’ll confirm the headset is connected to this device, then make sure Zoom is using it for both sound and microphone.',
    guidePhrase: 'Please confirm the headset shows as connected to the device running Zoom. Then, in Zoom, select that headset as both the Speaker and Microphone where those device choices are available.',
    confirmPhrase: 'Can you hear the meeting through the headset now, and can the other participants hear you through its microphone?',
    boundaryPhrase: 'If the headset cannot stay connected, fails outside Zoom, or requires managed driver or device changes, the next step belongs with device or IT support rather than deeper Zoom-only troubleshooting.',
  },
  {
    id: 'secure-connection',
    label: 'Secure Connection Error',
    routeId: 'secure-connection',
    opening: 'That exact secure-connection message has a specific Mac troubleshooting path. I’ll keep us to the approved steps and avoid changing managed settings without the right access.',
    guidePhrase: 'First let’s confirm you are on a Mac and that the exact message says “Unable to establish secure connection to Zoom.” If Zoom opens far enough to update, we’ll check the app update before moving to the approved reinstall path.',
    confirmPhrase: 'After the approved update or recovery step, does Zoom now open and connect without the secure-connection message?',
    boundaryPhrase: 'If the error remains after the approved recovery path, or the fix requires managed calendar integration, security software, network controls, or administrator access, please contact the appropriate IT or Zoom administrator.',
  },
  {
    id: 'transfer-device',
    label: 'Transfer to Another Device',
    routeId: 'transfer-device',
    opening: 'We’ll first make sure both devices are signed in to the same Zoom account. If transfer is available, the second device should show Switch for the meeting that is already in progress.',
    guidePhrase: 'On the second signed-in device, locate the meeting that is already in progress and look for Switch instead of the normal Join or Start action. Select Switch only after we confirm it is the same active meeting.',
    confirmPhrase: 'Did the meeting continue on the second device, and did the original device disconnect automatically?',
    boundaryPhrase: 'If Switch is unavailable because the account setting is disabled or managed, the account owner or Zoom administrator owns the next action. For Zoom Room transfer or pairing, use the full approved process rather than improvising.',
  },
  {
    id: 'join-muted',
    label: 'Join Muted',
    routeId: 'join-muted',
    opening: 'Do you want to join connected to audio but muted, or do you want Zoom not to connect to audio at all? Those are two different settings.',
    guidePhrase: 'If you want to hear the meeting but enter muted, use the mute-on-join setting for your device. If you want no Zoom audio connection for one meeting, use the Don’t connect to audio option instead.',
    confirmPhrase: 'When you join, are you getting the exact behavior you wanted—connected but muted, or not connected to Zoom audio?',
    boundaryPhrase: 'If the setting is missing or locked by organization policy, we should not try to force or bypass it. The Zoom administrator controls that setting.',
  },
  {
    id: 'join-video-preference',
    label: 'Camera On / Off on Join',
    routeId: 'join-video-preference',
    opening: 'Let’s first decide whether you want this camera behavior only for the next meeting or as your normal setting for future meetings.',
    guidePhrase: 'For a default behavior, use the approved Zoom join setting for keeping the camera off when joining. For a one-time meeting, use the video choice shown on the join screen instead of changing your normal preference.',
    confirmPhrase: 'On the next join screen, is the camera starting in the state you intended, and can you still change it before entering if needed?',
    boundaryPhrase: 'If the option is unavailable or controlled by organization policy, do not change managed settings. The Zoom administrator owns that policy decision.',
  },
  {
    id: 'meeting-volume',
    label: 'Meeting Volume',
    routeId: 'meeting-volume',
    opening: 'Is the whole Zoom meeting too loud or too quiet, or is it just one person? That tells us whether to adjust your Zoom volume or troubleshoot that participant’s microphone.',
    guidePhrase: 'If the whole meeting volume is the issue, adjust the Zoom speaker volume on desktop or the device volume on mobile. On Windows, use Volume Mixer only when the caller specifically wants Zoom louder or quieter than other apps.',
    confirmPhrase: 'Is the overall meeting now at a comfortable level through the speaker or headset you intended to use?',
    boundaryPhrase: 'If the device still cannot produce usable audio after the correct output and volume path are confirmed, move to the approved audio troubleshooting route. Do not add third-party volume software as a basic-support workaround.',
  },
  {
    id: 'auto-computer-audio',
    label: 'Auto Computer Audio',
    routeId: 'auto-computer-audio',
    opening: 'If you usually use the same computer speaker and microphone, we can have Zoom connect to computer audio automatically so you don’t have to choose it every time.',
    guidePhrase: 'In the Zoom desktop app, open the Join experience settings and enable Automatically connect to computer audio. Keep it off if you regularly need to choose a different audio method.',
    confirmPhrase: 'When you join the next eligible meeting, does Zoom connect directly to the computer speaker and microphone without showing the usual audio-method prompt?',
    boundaryPhrase: 'If the setting is missing or locked, it may be administrator-controlled. We should not bypass that policy; the Zoom administrator owns the next step.',
  },
  {
    id: 'multiple-audio-input-channels',
    label: 'Specific Audio Input Channels',
    routeId: 'multiple-audio-input-channels',
    opening: 'This option only appears when Zoom detects an eligible multi-channel input device. We’ll confirm the interface first, choose the channels, then save before testing.',
    guidePhrase: 'In Zoom Audio settings, select the intended multi-channel interface as the microphone. If Zoom detects at least three input channels, open the specific input-channel control, choose the channels you need, and save the selection before testing.',
    confirmPhrase: 'After saving, is Zoom using only the input channels you selected from that interface?',
    boundaryPhrase: 'If the channel option never appears, or the interface is not correctly recognized by the operating system, hardware, driver, routing, or managed-device troubleshooting belongs with device or IT support.',
  },
  {
    id: 'participants-before-join',
    label: 'Who Is Already in the Meeting?',
    routeId: 'participants-before-join',
    opening: 'Before we assume nobody is there, let’s confirm whether your account and Zoom Calendar setup support the pre-join participant view.',
    guidePhrase: 'If the required desktop account and calendar setup are available, open the scheduled meeting from Home or Calendar and check the participant or invitee information Zoom shows before joining.',
    confirmPhrase: 'Can you now see the participants Zoom reports as already joined, or did we identify a missing requirement for that feature?',
    boundaryPhrase: 'If the required setup is present but the participant view is still unavailable, use the organization’s Zoom Calendar or escalation path. Do not change account or calendar integrations without the caller’s authorization.',
  },
  {
    id: 'invite',
    label: 'Invite / Copy Link',
    routeId: 'invite',
    opening: 'I can show you where Zoom’s invite control is and how to copy the current meeting link. We’ll use the invitation Zoom provides without changing any meeting details.',
    guidePhrase: 'Open Participants and use the available Invite control. Then choose Copy invite link or Copy invitation when shown, and paste it only into the caller’s approved communication method.',
    confirmPhrase: 'Were you able to copy the current Zoom invitation or link exactly as Zoom provided it?',
    boundaryPhrase: 'If the Invite control is unavailable because of role or meeting policy, the host or organizer owns the next action. If the question is who should be allowed to attend, refer that decision to the designated proceeding contact.',
  },

]
