export const SCENARIO_SCRIPT_VERIFIED_AT = 'September 18, 2026'

export const SCENARIO_SCRIPTS = [
  {
    id: 'cant-join',
    label: 'Can’t Join',
    routeId: 'cant-join',
    opening: 'Let’s first confirm exactly where Zoom is stopping you. I’ll use the message on your screen to choose the correct joining path.',
    guidePhrase: 'If the invitation link is not working, let’s try the meeting details directly. Please open Zoom Workplace or zoom.us/join and enter the Meeting ID exactly as it was provided.',
    confirmPhrase: 'What do you see now—did Zoom accept the meeting details, or are you seeing a waiting screen or another message?',
    boundaryPhrase: 'We’ve completed the basic joining checks available to us. If Zoom still will not let you enter, the next step may need the meeting organizer to confirm access or your IT team to check a device or network restriction.',
  },
  {
    id: 'waiting-entry',
    label: 'Waiting to Get In',
    routeId: 'waiting-entry',
    opening: 'Let’s read the exact waiting message first, because “Waiting for host” and “Waiting Room” have different next steps.',
    guidePhrase: 'Please read the exact message on the Zoom screen to me. I’ll use that wording to determine whether we should wait for the host to start the meeting or whether admission is controlled by the host.',
    confirmPhrase: 'Does the message now show that the meeting has started, that you were admitted, or are you still on the same waiting screen?',
    boundaryPhrase: 'If you are in the Waiting Room or the meeting has not been started, that next action is controlled by the meeting host or organizer. We can explain the screen, but we cannot admit participants or start the organizer’s meeting.',
  },
  {
    id: 'cant-hear',
    label: 'Can’t Hear',
    routeId: 'cant-hear',
    opening: 'Since you’re already in the meeting, let’s check the audio path first. We’ll make sure Zoom is connected to the correct speaker before we look anywhere else.',
    guidePhrase: 'First, tell me whether you see Join Audio. If you do, please connect to meeting audio before we change any speaker setting.',
    confirmPhrase: 'Can you hear the meeting now, or can you hear Zoom’s speaker test through the device you selected?',
    boundaryPhrase: 'If Zoom is stable but there is still no sound after the approved audio checks, we’ll stop guessing and use the full approved audio process. If the device itself cannot produce sound, the next step belongs with the appropriate device or IT support.',
  },
  {
    id: 'cant-be-heard',
    label: 'They Can’t Hear Me',
    routeId: 'cant-be-heard',
    opening: 'Let’s check the microphone side first. We’ll confirm you’re unmuted, then make sure Zoom is listening to the correct microphone.',
    guidePhrase: 'Please look at the microphone control in Zoom. Does it say Mute or Unmute, and do you have any physical mute button on the headset or microphone?',
    confirmPhrase: 'Please speak normally for a moment. Does Zoom detect your voice, and can the other participants hear you now?',
    boundaryPhrase: 'If the device or operating system itself does not recognize the microphone after the basic checks, that is no longer limited to a Zoom setting. Please contact your IT or device support team for the system-level check.',
  },
  {
    id: 'camera-not-working',
    label: 'Camera',
    routeId: 'camera-not-working',
    opening: 'First let’s see whether your video is just turned off or whether Zoom is having trouble with the camera itself.',
    guidePhrase: 'Please look at the video control. If it says Start Video, select it once. If video is already on but the picture is black or missing, tell me that before we continue.',
    confirmPhrase: 'Do you see your camera preview now, and is it coming from the camera you intended to use?',
    boundaryPhrase: 'If the computer or phone itself does not recognize the camera, the remaining issue is outside a Zoom-only setting. The appropriate IT or device support team will need to check the hardware or system permission.',
  },
  {
    id: 'cant-share',
    label: 'Screen Share',
    routeId: 'cant-share',
    opening: 'Let’s first locate the Share control and confirm whether Zoom is blocking the action or whether the host controls the permission.',
    guidePhrase: 'Please look for Share or Share Screen in the meeting controls. Tell me whether you can select it and what happens when you do.',
    confirmPhrase: 'Can the other participants now see only the screen, application, or window you intended to share?',
    boundaryPhrase: 'If participant sharing is restricted by the host, we cannot bypass that permission. Please contact the meeting host or organizer. If the browser or operating system blocks screen capture, use the approved device permission path instead.',
  },
  {
    id: 'meeting-controls',
    label: 'Meeting Controls',
    routeId: 'meeting-controls',
    opening: 'Let’s identify the control you need and what buttons are visible on your Zoom screen before we assume anything is missing.',
    guidePhrase: 'Move your pointer inside the meeting window or tap the meeting if you are on mobile. Tell me which controls you can see, and we’ll locate the one you need from there.',
    confirmPhrase: 'Is the control visible now, and did opening it show the option you were trying to use?',
    boundaryPhrase: 'If the control is unavailable because of the caller’s role, host settings, account settings, or another permission boundary, we’ll stop there rather than trying to bypass the meeting configuration.',
  },
  {
    id: 'chat',
    label: 'Chat',
    routeId: 'chat',
    opening: 'Let’s locate Chat first and confirm whether the meeting currently allows the type of message you’re trying to send.',
    guidePhrase: 'Please open Chat from the meeting controls. Before sending anything, check the recipient so the message goes only to the person or group you intend.',
    confirmPhrase: 'Do you see the Chat panel now, and did the message go to the intended recipient?',
    boundaryPhrase: 'If Chat or a specific chat option is disabled by the host or account administrator, we cannot enable that permission from basic support. The meeting host or appropriate administrator owns that next step.',
  },
  {
    id: 'reactions',
    label: 'Reactions / Raise Hand',
    routeId: 'reactions',
    opening: 'Let’s open the reactions menu first. If you’re raising your hand, I’ll also show you how to lower it afterward because that one stays active until it’s cleared.',
    guidePhrase: 'Please look for React or Reactions. On mobile, check More if you do not see it on the main controls. Tell me when the reaction choices are visible.',
    confirmPhrase: 'Can you see the raised-hand indicator or the reaction you selected, and do you know how to remove it when you’re finished?',
    boundaryPhrase: 'If reactions are unavailable because the host or account administrator has disabled them, that is a meeting or account permission boundary and we should not try to bypass it.',
  },
]
