import { useEffect, useState } from 'react'
import { loadFeedback, loadTeam, loadUsage } from '../../lib/adminApi'
import { avatarUrl } from '../profile/avatarCatalog'

function useData(loader) {
  const [state, setState] = useState({ loading: true, data: null, error: '' })
  useEffect(() => { let live = true; loader().then((data) => live && setState({ loading: false, data, error: '' })).catch((error) => live && setState({ loading: false, data: null, error: error.message })); return () => { live = false } }, [loader])
  return state
}
function State({ state, children }) { if (state.loading) return <p>Loading secure data…</p>; if (state.error) return <p role="alert">{state.error}</p>; return children(state.data) }

export function AdminHome({ onNavigate }) { return <section className="console-view"><p className="eyebrow">JA workspace</p><h1>Admin Home</h1><p>Manage the real team, review privacy-safe usage, and respond to submitted feedback.</p><div className="admin-shortcuts"><button onClick={() => onNavigate('team')}><strong>Team Management</strong><span>Accounts, invites and access →</span></button><button onClick={() => onNavigate('usage')}><strong>Usage Analytics</strong><span>Real Console activity →</span></button><button onClick={() => onNavigate('feedback_queue')}><strong>Feedback Queue</strong><span>Agent reports and context →</span></button></div></section> }
export function TeamManagement() { const state = useData(loadTeam); return <section className="console-view"><p className="eyebrow">JA only</p><h1>Team Management</h1><State state={state}>{(team) => <div className="team-list">{team.map((person) => <article key={person.id}>{avatarUrl(person.avatar_id) ? <img src={avatarUrl(person.avatar_id)} alt="" /> : <span className="avatar-fallback">{person.initials}</span>}<div><strong>{person.username}</strong><small>{person.initials} · {person.role === 'creator_admin' ? 'JA Admin' : 'Agent'}</small></div><span className={`status-badge ${person.status}`}>{person.status}</span></article>)}</div>}</State></section> }
export function UsageAnalytics() { const state = useData(loadUsage); return <section className="console-view"><p className="eyebrow">Privacy-safe metadata</p><h1>Usage Analytics</h1><State state={state}>{(data) => <><div className="real-summary"><div><strong>{data.events.length}</strong><span>recent recorded events</span></div><div><strong>{data.presence.filter((presence) => presence.state === 'active').length}</strong><span>active now</span></div><div><strong>{data.presence.filter((presence) => presence.state === 'idle').length}</strong><span>idle</span></div></div><p>Counts use identifiers and timestamps only; no support-call content is tracked.</p></>}</State></section> }
export function FeedbackQueue() { const state = useData(loadFeedback); return <section className="console-view"><p className="eyebrow">JA only</p><h1>Feedback Queue</h1><State state={state}>{(items) => items.length ? <div className="feedback-list">{items.map((item) => <article key={item.id}><header><strong>{item.type.replaceAll('_', ' ')}</strong><span>{item.status}</span></header><p>{item.what_noticed}</p>{item.suggested_change && <p><b>Suggestion:</b> {item.suggested_change}</p>}<small>{item.page_label}{item.process_id ? ` · ${item.process_id}` : ''}</small></article>)}</div> : <div className="empty-state"><h2>No feedback submitted yet</h2></div>}</State></section> }
