export const READINESS_PARTS = [
  {
    id: 'foundation-call-flow',
    number: 1,
    title: 'Foundation & Call Flow',
    shortTitle: 'Call Flow',
    purpose: 'Can the agent follow the Ogletree call structure before, during, and after troubleshooting?',
    status: 'available',
  },
  {
    id: 'device-navigation',
    number: 2,
    title: 'Device & Navigation Awareness',
    shortTitle: 'Devices',
    purpose: 'Can the agent recognize platform differences and locate the right controls without guessing?',
    status: 'planned',
  },
  {
    id: 'troubleshooting-judgment',
    number: 3,
    title: 'Troubleshooting Judgment',
    shortTitle: 'Troubleshooting',
    purpose: 'Can the agent choose the next approved action from the caller’s symptom and observed result?',
    status: 'planned',
  },
  {
    id: 'scope-referral',
    number: 4,
    title: 'Scope & Referral Judgment',
    shortTitle: 'Scope',
    purpose: 'Can the agent recognize the support boundary and identify the correct next owner?',
    status: 'planned',
  },
  {
    id: 'live-call-readiness',
    number: 5,
    title: 'Live Call Readiness',
    shortTitle: 'Live Call',
    purpose: 'Can the agent combine call flow, discovery, guidance, confirmation, documentation, and boundary judgment?',
    status: 'planned',
  },
]

export const FOUNDATION_QUESTIONS = [
  {
    id: 'listen-before-troubleshoot',
    type: 'Scenario',
    prompt: 'A caller says their camera is not working and immediately starts explaining what happened. What should the agent do before beginning technical troubleshooting?',
    options: [
      { id: 'a', text: 'Open Zoom video settings immediately and start changing camera options.' },
      { id: 'b', text: 'Let the caller explain the concern, then acknowledge what you heard before troubleshooting.' },
      { id: 'c', text: 'Ask the caller to restart Zoom before gathering any more information.' },
      { id: 'd', text: 'Move directly to referral because camera issues may involve the device.' },
    ],
    correctOptionId: 'b',
    explanation: 'The Ogletree flow places Active Listening & Acknowledgment before empathy, ownership, identification, diagnosis, and troubleshooting. The caller should be allowed to explain the concern before technical steps begin.',
    locationLabel: 'Training & Resources → Scripts & Communication → Call Language → Listen & Acknowledge',
    resourceTarget: { view: 'training', section: 'scripts', mode: 'language', subsection: 'listen' },
    source: 'Ogletree – Tier 1 Zoom Support · Standard Call Flow Outline',
  },
  {
    id: 'identify-hearing-context',
    type: 'Context check',
    prompt: 'The caller says, “My hearing has already started. Everyone else can hear each other, but I can’t hear them.” Which context should the agent identify early before choosing the troubleshooting route?',
    options: [
      { id: 'a', text: 'Only the caller’s name and phone number.' },
      { id: 'b', text: 'The device, Zoom app or browser, hearing status, and whether other participants are affected.' },
      { id: 'c', text: 'Only the Zoom version number.' },
      { id: 'd', text: 'The subject of the arbitration and who is expected to win.' },
    ],
    correctOptionId: 'b',
    explanation: 'Caller & Hearing Identification includes the device, Zoom application/browser, whether the hearing has started, and whether other participants are affected. Hearing status is important because urgency may change during an active hearing.',
    locationLabel: 'Training & Resources → Scripts & Communication → Call Language → Identify Caller / Hearing',
    resourceTarget: { view: 'training', section: 'scripts', mode: 'language', subsection: 'identify' },
    source: 'Ogletree – Tier 1 Zoom Support · Standard Call Flow Outline',
  },
  {
    id: 'diagnose-before-action',
    type: 'Sequence',
    prompt: 'The agent has greeted the caller, listened, acknowledged the concern, shown empathy, and explained that they will help. What comes next before troubleshooting?',
    options: [
      { id: 'a', text: 'Identify the caller/hearing context and probe to diagnose the specific problem.' },
      { id: 'b', text: 'Recap the call and ask the final-check question.' },
      { id: 'c', text: 'Start with the most common fix for that symptom.' },
      { id: 'd', text: 'Document the call outcome before asking more questions.' },
    ],
    correctOptionId: 'a',
    explanation: 'The standard sequence moves from Assurance / Ownership to Caller & Hearing Identification, then Probing / Diagnostic Questions, and only then to Troubleshooting.',
    locationLabel: 'Training & Resources → Guided Visual Lessons → Follow the Ogletree call flow before troubleshooting',
    resourceTarget: { view: 'training', section: 'lessons' },
    source: 'Ogletree – Tier 1 Zoom Support · Standard Call Flow Outline',
  },
  {
    id: 'confirm-before-close',
    type: 'Outcome check',
    prompt: 'After a troubleshooting step, the caller says, “I think it’s okay now.” What should the agent do next?',
    options: [
      { id: 'a', text: 'Close the call immediately because the caller said it seems okay.' },
      { id: 'b', text: 'Start a different troubleshooting route to make sure nothing else is wrong.' },
      { id: 'c', text: 'Ask the caller to confirm the exact function is working before recap, final check, and closing.' },
      { id: 'd', text: 'Mark the issue unresolved until the caller calls back later.' },
    ],
    correctOptionId: 'c',
    explanation: 'Confirmation of Resolution comes before recap and closing. The flow explicitly says not to assume the issue is fixed; the caller should confirm the function that was failing.',
    locationLabel: 'Training & Resources → Scripts & Communication → Call Language → Confirm Resolution',
    resourceTarget: { view: 'training', section: 'scripts', mode: 'language', subsection: 'confirm-resolution' },
    source: 'Ogletree – Tier 1 Zoom Support · Standard Call Flow Outline',
  },
]
