export const READINESS_PARTS = [
  {
    id: 'general-zoom-scenarios',
    number: 1,
    title: 'General Zoom Scenarios',
    shortTitle: 'Zoom Scenarios',
    purpose: 'Can the agent recognize the right support direction from common Zoom symptoms without relying on a specific client setting?',
    status: 'available',
  },
  {
    id: 'device-navigation',
    number: 2,
    title: 'Device & Navigation Awareness',
    shortTitle: 'Devices',
    purpose: 'Can the agent recognize platform differences and locate the right controls without guessing?',
    status: 'planned',
  },
  {
    id: 'troubleshooting-judgment',
    number: 3,
    title: 'Troubleshooting Judgment',
    shortTitle: 'Troubleshooting',
    purpose: 'Can the agent choose the next approved action from the caller’s symptom and observed result?',
    status: 'planned',
  },
  {
    id: 'scope-referral',
    number: 4,
    title: 'Scope & Referral Judgment',
    shortTitle: 'Scope',
    purpose: 'Can the agent recognize the support boundary and identify the correct next owner?',
    status: 'planned',
  },
  {
    id: 'live-call-readiness',
    number: 5,
    title: 'Live Call Readiness',
    shortTitle: 'Live Call',
    purpose: 'Can the agent combine discovery, troubleshooting, confirmation, documentation, and boundary judgment in a realistic support call?',
    status: 'planned',
  },
]
